### ISSUE TITLE
Point of contention on The Analysis

### ISSUE THREAD

**Issue by space-penguin** [glitchassassin/cold-hard-facts#1]
The second bullet in the analysis points out that Wikileaks also has a motive to sow confusion over who the whistleblower could be.  While Wikileaks may be playing coy about whether the source is Rich they are essentially saying it is Rich in a way that legalistically conforms with how they treat revelation of sources.  It should be asked if it is in Wikileaks character or mission to falsely malign the dead. To my knowledge it is not but I have to admit I have not diligently researched this point.

Thank you for the analysis I really appreciate this type of break down of events, also I really like Lackey, I have been using AutoIt, OpenCV, Python and other tools to automate tasks for quite a while and am sure I will find use for Lackey in the future.

**Comment by glitchassassin** [comment]
That's a valid point. I think the legalism could cut both ways: they aren't "technically" revealing he's a source, but neither are they "technically" maligning Rich by calling him a whistleblower. (You could also question whether that would really be "maligning," from their perspective, if Wikileaks believes whistleblowers are really heroes.)

In any case, this is all speculation: I'm just offering a couple plausible explanations for the few facts that have come out. I'll leave it to everyone whether or not to draw conclusions from what we know.

Cheers!
